
language: python
sudo: false

env:
    - LUA="lua=5.1"
    - LUA="lua=5.2"
    - LUA="lua=5.3"
    - LUA="luajit=2.0"
    - LUA="luajit=2.1"

install:
    - luarocks install moonscript
    - luarocks install busted
    - luarocks install luacov
    - luarocks install luacov-coveralls

before_install:
    - pip install hererocks
    - hererocks lua_install -r^ --$LUA
    - export PATH=$PATH:$PWD/lua_install/bin

script:
    - busted --verbose spec/*.moon --coverage

after_success:
    - luacov-coveralls -i "%.moon" -e "spec"

