
language: c
sudo: false

env:
    global:
        - LUAROCKS=2.4.1
    matrix:
        - LUA="lua=5.1"
        - LUA="lua=5.2"
        - LUA="lua=5.3"
        - LUA="luajit=2.0"
        - LUA="luajit=2.1"

install:
    - source .travis/setenv_lua.sh
    - luarocks install moonscript
    - luarocks install busted

script:
    - busted --verbose spec/*.moon

notifications:
    email:
        on_success: change
        on_failure: always

